apiVersion: apps/v1
kind: Deployment
metadata:
   name: python-app
   labels:
      app: python-app
spec:
   replicas: 2
   selector:
      matchLabels:
         app: python-app
   template:
      metadata:
         labels:
            app: python-app
      spec:
          containers:
           -  name: python-app 
              image: johntoby/python-app:latest 
              imagePullPolicy: Always
              ports:
              - containerPort: 5000
              resources:
               limits:
                  memory: "512Mi"
                  cpu: "500m"
               requests:
                  memory: "256Mi"
                  cpu: "250m" 